apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/pingpong_postgres/configmap.yaml
- manifests/pingpong_postgres/service.yaml
- manifests/pingpong_postgres/statefulset.yaml
- manifests/pingpong_postgres/volumeclaim.yaml
- manifests/pingpong/deployment.yaml
- manifests/pingpong/service.yaml
- manifests/log_output/service.yaml
- manifests/log_output/deployment.yaml
- manifests/log_output_reader/deployment.yaml
- manifests/log_output_reader/service.yaml
- manifests/log_output_reader/configmap.yaml
- manifests/shared_ingress.yaml
images:
- name: PROJECT/IMAGE
  newName: viksil/pingpong
  newTag: f25e8bf71c8c141b7ab69f0f6acb55c98965a123
- name: PROJECT1/IMAGE1
  newName: viksil/log_output
  newTag: f25e8bf71c8c141b7ab69f0f6acb55c98965a123
- name: PROJECT2/IMAGE2
  newName: viksil/log_output_reader
  newTag: f25e8bf71c8c141b7ab69f0f6acb55c98965a123
